-- Creates all the tables for the database.
-- Zachary Wolfe
-- Matt Taylor

-- ORDER TABLE

CREATE TABLE `ORDER` (
  -- Keys of ORDER
  PRIMARY KEY (ORDER_ID),
  FOREIGN KEY 
    (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),

  -- Attributes of ORDER
  ORDER_ID INT AUTO_INCREMENT,
  TOTAL_PRICE DECIMAL(10, 2),
  BUSINESS_COST DECIMAL(10, 2)
);

-- 
--        TYPES OF ORDERS
-- 

-- DINE_IN TABLE
CREATE TABLE DINE_IN (
  -- Keys of DINE_IN
  PRIMARY KEY (ID)
  FOREIGN KEY
    (ID) REFERENCES ORDER(ORDER_ID),
  
  -- Attributes of DINE_IN
  ID INT AUTO_INCREMENT,
  TABLE_NUMBER INT
);

-- DELIVERY TABLE
CREATE TABLE DELIVERY (
  -- Keys of DELIVERY
  PRIMARY KEY (ID)
  FOREIGN KEY
    (ID) REFERENCES ORDER(ORDER_ID),

  -- Attributes of DELIVERY
  ID INT AUTO_INCREMENT
);

-- PICKUP TABLE
CREATE TABLE PICKUP (
  -- Keys of PICKUP
  PRIMARY KEY (ID)
  FOREIGN KEY
    (ID) REFERENCES ORDER(ORDER_ID),

  -- Attributes of PICKUP
  ID INT AUTO_INCREMENT
);



CREATE TABLE SEATS (
  -- Keys of SEATS
  PRIMARY KEY (SEAT_ID),
  FOREIGN KEY
    (SEAT_ID) REFERENCES DINE_IN(ID),
  
  -- Attributes of SEATS
  SEAT_ID INT AUTO_INCREMENT,
  SEAT_NUMBER INT
);

CREATE TABLE CUSTOMER (
  -- Keys of CUSTOMER
  PRIMARY KEY (CUSTOMER_ID),
  
  -- Attributes of CUSTOMER
  CUSTOMER_ID INT AUTO_INCREMENT,
  PHONE_NUMBER VARCHAR(10),
  ADDRESS VARCHAR(100),
  NAME VARCHAR(100)
);

CREATE TABLE ORDER_DISCOUNT (
  -- Keys of ORDER_DISCOUNT
  PRIMARY KEY (ID),
  FOREIGN KEY 
    (DISCOUNT_ID) REFERENCES DISCOUNT(DISCOUNT_ID),
  
  -- Attributes of ORDER_DISCOUNT
  ID INT AUTO_INCREMENT,
  DISCOUNT_ID INT
);

CREATE TABLE DISCOUNT (
  -- Keys of DISCOUNT
  PRIMARY KEY (DISCOUNT_ID),

  -- Attributes of DISCOUNT
  DISCOUNT_ID INT AUTO_INCREMENT,
  NAME VARCHAR(50),
  PERCENT_OFF(3, 2),
  DOLLAR_OFF(10, 2)
);


-- NOT SURE ON THIS ONE.
CREATE TABLE PIZZA_DISCOUNT (
  -- Keys of PIZZA_DISCOUNT
  FOREIGN KEY
    (DISCOUNT_ID) REFERENCES DISCOUNT(DISCOUNT_ID),
  FOREIGN KEY
    (PIZZA_ID) REFERENCES PIZZA(PIZZA_ID)
);


CREATE TABLE PIZZA (
  -- Keys of PIZZA
  PRIMARY KEY (PIZZA_ID),
  FOREIGN KEY
    (ORDER_ID) REFERENCES ORDER(ORDER_ID),

  -- Attributes of PIZZA
  PIZZA_ID INT AUTO_INCREMENT,
  CRUST_TYPE VARCHAR(50),
  PRICE DECIMAL(10, 2),
  SIZE VARCHAR(25),
  BUSINESS_COST DECIMAL(10,2),
  STATUS VARCHAR(25),
  TIME_STAMP TIMESTAMP
);

CREATE TABLE BASE_PRICE (
  -- Keys of BASE_PRICE
  PRIMARY KEY (CRUST_TYPE),
  FOREIGN KEY
    (SIZE) REFERENCES PIZZA(SIZE),
  
  -- Attributes of BASE_PRICE
  CRUST_TYPE VARCHAR(50),
  SIZE VARCHAR(25),
  PRICE DECIMAL(10, 2),
  BASE_COST DECIMAL(10, 2)
);

CREATE TABLE TOPPINGS (
  -- Keys of TOPPINGS
  PRIMARY KEY (NAME),

  -- Attributes of TOPPINGS
  NAME VARCHAR(50),
  PRICE DECIMAL(10, 2),
  BUSINESS_COST DECIMAL(10, 2),
  INVENTORY_LEVEL INT,
  AMOUNT DECIMAL(5, 2),
);

CREATE TABLE HAS_TOPPING (
  PRIMARY KEY (NAME),
  FOREIGN KEY
    (PIZZA_ID) REFERENCES PIZZA(PIZZA_ID),
  
  -- Attributes of HAS_TOPPING
  NAME VARCHAR(50),
  PIZZA_ID INT,
  REQUIRES_DOUBLE BOOLEAN
);