-- Drops all the data from each table as mentioned in the instruction from the handout

DROP TABLE HAS_TOPPING;

DROP TABLE TOPPINGS;

DROP TABLE PIZZA_DISCOUNT;

DROP TABLE PIZZA;

DROP TABLE BASE_PRICE;

DROP TABLE ORDER_DISCOUNT;

DROP TABLE DISCOUNT;

DROP TABLE SEATS;

DROP TABLE DINE_IN;

DROP TABLE DELIVERY;

DROP TABLE PICKUP;

DROP TABLE ORDERS;

DROP TABLE CUSTOMERS;