SELECT TOPPING_NAME, INVENTORY_LEVEL, INVENTORY_LEVEL / AMOUNT_XLarge AS CAN_MAKE_XLARGE
  FROM TOPPINGS
  ORDER BY TOPPING_NAME ASC;

SELECT SUM(PRICE) AS TOTAL_PRICE, SUM(BUSINESS_COST) AS TOTAL_EXPENSES, TOTAL_PRICE - TOTAL_EXPENSES AS TOTAL_PROFIT
  FROM ORDERS;